In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8208, 2911, 9345, 1719],
 [8208, 2911, 9345, 9311],
 [8208, 1583, 9345, 2514],
 [8664, 7880, 5906, 322, 9761],
 [8664, 7880, 5906, 322, 2446],
 [1686, 8208, 4274, 9345, 9912],
 [4617, 3994, 5879, 322]]

In [11]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8208 2911 9345 1719]
 [   0    0    0    0 8208 2911 9345 9311]
 [   0    0    0    0 8208 1583 9345 2514]
 [   0    0    0 8664 7880 5906  322 9761]
 [   0    0    0 8664 7880 5906  322 2446]
 [   0    0    0 1686 8208 4274 9345 9912]
 [   0    0    0    0 4617 3994 5879  322]]


In [14]:
## feature representation
dim=10

In [23]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim,input_length=sent_length))


In [24]:
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
embedding_vectors = model.predict(embedded_docs)
embedding_vectors

1/1 [==============================] - 0s 18ms/step


array([[[-0.03900959, -0.01003162, -0.02506214,  0.01458435,
         -0.04611048,  0.03770779, -0.03182194,  0.01541984,
          0.03541111,  0.00464509],
        [-0.03900959, -0.01003162, -0.02506214,  0.01458435,
         -0.04611048,  0.03770779, -0.03182194,  0.01541984,
          0.03541111,  0.00464509],
        [-0.03900959, -0.01003162, -0.02506214,  0.01458435,
         -0.04611048,  0.03770779, -0.03182194,  0.01541984,
          0.03541111,  0.00464509],
        [-0.03900959, -0.01003162, -0.02506214,  0.01458435,
         -0.04611048,  0.03770779, -0.03182194,  0.01541984,
          0.03541111,  0.00464509],
        [-0.04621823, -0.00306954, -0.02388828,  0.00356521,
         -0.01829448, -0.01469499,  0.02054666,  0.00252283,
          0.0172184 ,  0.03445548],
        [-0.03614642,  0.03135834, -0.02645149, -0.03950789,
         -0.00226998,  0.00065339, -0.0206195 ,  0.01403775,
          0.04603244, -0.03152938],
        [ 0.0023319 , -0.02964399,  0.0086187 ,  0.0

In [ ]:
print("Shape of embedding vectors:", embedding_vectors.shape)
# Output shape:
# (number_of_sentences, sentence_length, embedding_dim)
# Example: (7, 8, 10)
# Each word in a sentence now has a 10-dimensional vector.

Shape of embedding vectors: (7, 8, 10)


In [22]:
print("Embedding for first sentence:\n", embedding_vectors[0])

Embedding for first sentence:
 [[-0.03900959 -0.01003162 -0.02506214  0.01458435 -0.04611048  0.03770779
  -0.03182194  0.01541984  0.03541111  0.00464509]
 [-0.03900959 -0.01003162 -0.02506214  0.01458435 -0.04611048  0.03770779
  -0.03182194  0.01541984  0.03541111  0.00464509]
 [-0.03900959 -0.01003162 -0.02506214  0.01458435 -0.04611048  0.03770779
  -0.03182194  0.01541984  0.03541111  0.00464509]
 [-0.03900959 -0.01003162 -0.02506214  0.01458435 -0.04611048  0.03770779
  -0.03182194  0.01541984  0.03541111  0.00464509]
 [-0.04621823 -0.00306954 -0.02388828  0.00356521 -0.01829448 -0.01469499
   0.02054666  0.00252283  0.0172184   0.03445548]
 [-0.03614642  0.03135834 -0.02645149 -0.03950789 -0.00226998  0.00065339
  -0.0206195   0.01403775  0.04603244 -0.03152938]
 [ 0.0023319  -0.02964399  0.0086187   0.00253954 -0.03186456 -0.0054441
   0.01353167 -0.02949181  0.0397421   0.02080778]
 [-0.04705814  0.01622352 -0.03826337 -0.04654224 -0.01525055 -0.04150872
   0.01884064  0.0386